import { Platform, StyleSheet } from "react-native";

export const AlertScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fa",
  },
  header: {
    padding: 16,
    marginBottom: 10,
    paddingTop: Platform.OS === "android" ? 40 : 20,
    marginTop: Platform.OS === "ios" ? 30 : 0,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerLogo: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  viewMapButton: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 30,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  viewMapButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  sosButton: {
    backgroundColor: "red",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 30,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  refreshButton: {
    backgroundColor: "#3b82f6",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 10,
    alignSelf: "center",
  },
  refreshButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  alertItem: {
    backgroundColor: "white",
    borderRadius: 10,
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 4,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderLeftWidth: 5,
  },
  alertItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  alertType: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3b82f6",
  },
  alertTimestamp: {
    fontSize: 12,
    color: "#666",
  },
  alertDescription: {
    fontSize: 14,
    color: "#333",
    marginBottom: 10,
  },
  alertLocationSnippet: {
    fontSize: 12,
    color: "#777",
    fontStyle: "italic",
  },
  alertFooter: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  viewDetailsHint: {
    fontSize: 12,
    color: "#3b82f6",
    fontWeight: "600",
  },
  medicalAlert: {
    borderLeftColor: "#e53935",
    color: "#e53935",
  },
  safetyAlert: {
    borderLeftColor: "#f57c00",
    color: "#f57c00",
  },
  otherAlert: {
    borderLeftColor: "#1e88e5",
    color: "#1e88e5",
  },
  emptyListText: {
    textAlign: "center",
    marginTop: 30,
    fontSize: 16,
    color: "#666",
  },
});
